### ISSUE TITLE
Scene Root Objects

### ISSUE THREAD

**Issue by JulianKnodt** [lo48576/fbxcel-dom#21]
It seems the way that root objects are currently gotten can lead to null object handles on the scene. I'm not sure if a total rewrite is still planned, but at least the way [Assimp](https://github.com/assimp/assimp) handles this is that `0` is hardcoded as the root, and it starts by looking for objects with the `Model` class which have a parent of `0` (See FBXConverter.cpp, ConvertRootNode). I would recommend that this be added to the document struct since that knowledge is hard to dig up.

**Comment by lo48576** [comment]
Thank you for pointing out.

The way I think the users should do is:

1. Get [`SceneHandle`](https://docs.rs/fbxcel-dom/latest/fbxcel_dom/v7400/object/scene/struct.SceneHandle.html)s (which are scene nodes of course) by [`Document::scene`](https://docs.rs/fbxcel-dom/latest/fbxcel_dom/v7400/struct.Document.html#method.scenes)
2. Get the object ID or the object handle by [`SceneHandle::root_object_id`](https://docs.rs/fbxcel-dom/latest/fbxcel_dom/v7400/object/scene/struct.SceneHandle.html#method.root_object_id) or [`SceneHandle::root_object`](https://docs.rs/fbxcel-dom/latest/fbxcel_dom/v7400/object/scene/struct.SceneHandle.html#method.root_object) methods
3. Access that node as `Model` class

I didn't hardcode `0` as the parent of a root node because I've found the `Documents` node that seems to have root node IDs. This implies the possibility of root node ID not being `0`... while I've never seen such a weird FBX file.

(The below is the screenshot of a part of a FBX file structure inspected by [fbx-tree-view](https://github.com/lo48576/fbx-tree-view).)

![2024-12-14-164133+0900](https://github.com/user-attachments/assets/da766c95-a876-4333-8d4b-63a3efe566ca)

But yeah, the current document provides no hints about such usage, so some instructions to use the object trees would be very useful.

The problem is, I've actually have no experiences either to write the practical applications that traverse objects tree in a scene nor to create any models using 3D modeling software, so I don't know the real and typical workflow on a FBX file... This library is solely based on my (non-battle-tested) knowledge and observation on FBX file structure.

**Comment by lo48576** [comment]
By the way:

> I'm not sure if a total rewrite is still planned,

I've been (and still I am) away from things related to 3D rendering for long time, just because I have other things I want to do, I have not enough time to work on this area, and most importantly, I have too little experience and insights on practical and advanced 3D data usage on real applications.
I'm afraid I won't work on this library in the foreseeable future.

**Comment by JulianKnodt** [comment]
Thanks for the reply, it's quite difficult to figure out the structure of FBX files since there's no clear docs. I ended up starting my own FBX parser [here](https://github.com/JulianKnodt/pars3d). The GUI tool you made seems pretty useful for figuring out what features are under each node, but I've found that sometimes they are optional, so it probably takes a lot of example FBX files to test them. I've exported a cube from blender and am testing it, but eventually I may end up testing some from Sketchfab.

I'm mostly using it for geometry processing research, which is quite different from FBX's usual usage for rendering, but a lot of data is in the FBX format so it's nice to be able to process it.
